### ISSUE TITLE
Update Masonry

### ISSUE THREAD

**Issue by sylfabre** [components/components#16]
https://github.com/desandro/masonry

Thanks !

**Comment by sylfabre** [comment]
And it seems that it's not in packagist anymore :/

**Comment by desandro** [comment]
Masonry is already supported by Bower. Package manager support for NPM and Browserify is coming, but slowly. Please open issues on the Masonry repo for any requests https://github.com/desandro/masonry/issues . No need to shim repos here.

**Comment by sylfabre** [comment]
@desandro What about composer ?
