### ISSUE TITLE
Unable to install components/mousetrap

### ISSUE THREAD

**Issue by fza** [components/components#22]
Sorry for posting this in here, but [components/mousetrap](https://github.com/components/mousetrap) doesn't have an issue tracker. Anyway: Using the latest component 1.0.0rc6 I am unable to install `components/mousetrap`. It always gives me:

```
$ component install components/mousetrap
fatal : Object mousetrap.js has no method 'replace'
```

I never had this problem before and can't figure out what it might be since mousetrap's [component.json](https://github.com/components/mousetrap/blob/master/component.json) seems to be OK. Sometimes this error even pops up with component 0.19.9. Is this an error with component itself or mousetrap?

**Comment by RobLoach** [comment]
Let's discuss over there :+1: .
