### ISSUE TITLE
Request: bootbox

### ISSUE THREAD

**Issue by sagikazarmark** [components/components#31]
https://github.com/makeusabrew/bootbox

There is already a bootbox [fork](https://github.com/tubssp/bootbox) which uses the components vendor on [Packagist](https://packagist.org/packages/components/bootbox), but it is not updated since last June and it would be awesome to see it in the original components organization.

/cc @tubssp

**Comment by RobLoach** [comment]
@sagikazarmark Would be even awesomer to have `composer.json` directly in the source package. Then `/components` wouldn't need to mirror it. See the PR above.

**Comment by sagikazarmark** [comment]
Yeah, indeed it would be better.

**Comment by RobLoach** [comment]
https://packagist.org/packages/makeusabrew/bootbox
